In [1]:
import numpy as np

### Arrays basics

In [2]:
arr_1 = [1, 2, 3, 4, 5]

#1-d array
np_arr_1 = np.array(arr_1, dtype=np.int8)
np_arr_1

array([1, 2, 3, 4, 5], dtype=int8)

In [3]:
multi_arr = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

#multi dim array here, 2D
np_multi_arr = np.array(multi_arr)
np_multi_arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
#Defining the start value, stop value
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
# with start, end and no. of values here, with
# 0 to 5 and 7 values in between
np.linspace(0, 5, 7)

array([0.        , 0.83333333, 1.66666667, 2.5       , 3.33333333,
       4.16666667, 5.        ])

In [6]:
np.zeros(4) # 1D array of zeroes

array([0., 0., 0., 0.])

In [7]:
np.zeros((2, 3)) # 2D 2x3 matrix of zeroes

array([[0., 0., 0.],
       [0., 0., 0.]])

In [8]:
np.ones((3, 4)) #same thing for ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [9]:
# identity matrix
np.eye(3, 3, dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [10]:
#find the size -> gives no. of elements in array
np_multi_arr.size

9

In [11]:
np_multi_arr.dtype

dtype('int32')

In [12]:
# random values-> 7 item array from 10 to 50
np.random.randint(10, 50, 7)

array([16, 26, 45, 34, 13, 31, 36])

In [13]:
np.random.randint(10, 50, size=(2, 3)) # multi dim array

array([[20, 31, 40],
       [36, 33, 28]])

### Slicing and indexing basics

In [14]:
#shape of array
multi_arr = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

#multi dim array here, 2D
np_multi_arr = np.array(multi_arr)

np_multi_arr, np_multi_arr.shape

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 (3, 3))

In [15]:
# get element by index
np_multi_arr[0, 2]

3

In [16]:
np_multi_arr.item(0, 2)

3

In [17]:
# get specific indices, the indices list indicates 
# the indices of the values to extract
np.take(np_multi_arr, [0, 2, 4])

array([1, 3, 5])

In [18]:
np_arr_1[3: 5] #use like a normal list

array([4, 5], dtype=int8)

In [19]:
np_arr_1[:4]

array([1, 2, 3, 4], dtype=int8)

In [20]:
# reverse the array
np_arr_1[::-1]

array([5, 4, 3, 2, 1], dtype=int8)

In [21]:
np_multi_arr[:, 0] #first column from all rows

array([1, 4, 7])

In [22]:
#perform comparisons
np_multi_arr[np_multi_arr > 4]

array([5, 6, 7, 8, 9])

In [23]:
#multiple comparisons
np_multi_arr[(np_multi_arr > 4) & (np_multi_arr < 8)]

array([5, 6, 7])

In [24]:
# replace elements at indices 0, 3, 5 with values 2, 2, 2
np.put(np_multi_arr, [0, 3, 5], [2, 2, 2])

In [25]:
np_multi_arr

array([[2, 2, 3],
       [2, 5, 2],
       [7, 8, 9]])

In [26]:
# unique values
np.unique(np_multi_arr)

array([2, 3, 5, 7, 8, 9])

### Reshaping business

In [27]:
# reshape 9x9 array into 9X1 
np_multi_arr = np_multi_arr.reshape((9, 1))
np_multi_arr

array([[2],
       [2],
       [3],
       [2],
       [5],
       [2],
       [7],
       [8],
       [9]])

In [28]:
#shape of array
multi_arr = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

#multi dim array here, 2D
np_multi_arr = np.array(multi_arr)

np_multi_arr, np_multi_arr.shape

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 (3, 3))

In [29]:
np.resize(np_multi_arr, (2, 5)) 
#only returns the value, 
#does not modify the original array

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 1]])

In [30]:
np_multi_arr #still the same. 

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
np_multi_arr.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [32]:
np_multi_arr.swapaxes(0, 1) #same as transpose for a 2d array

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [33]:
np_multi_arr.flatten('F')

'''
Parameters
order{‘C’, ‘F’, ‘A’, ‘K’} are optional
‘C’ means to flatten in row-major (C-style) order. 
‘F’ means to flatten in column-major (Fortran- style) order. 
‘A’ means to flatten in column-major order 
if a is Fortran contiguous in memory, row-major order otherwise. 
‘K’ means to flatten a in 
the order the elements occur in memory. The default is ‘C’.
'''

'\nParameters\norder{‘C’, ‘F’, ‘A’, ‘K’} are optional\n‘C’ means to flatten in row-major (C-style) order. \n‘F’ means to flatten in column-major (Fortran- style) order. \n‘A’ means to flatten in column-major order \nif a is Fortran contiguous in memory, row-major order otherwise. \n‘K’ means to flatten a in \nthe order the elements occur in memory. The default is ‘C’.\n'

In [34]:
np_multi_arr.sort(axis = 1)
np_multi_arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Stacking and splitting thingies

In [35]:
arr = np.random.randint(10, size=(2, 3))
arr

array([[3, 9, 2],
       [2, 2, 2]])

In [36]:
arr2 = np.random.randint(10, size=(2, 3))
arr2

array([[0, 4, 2],
       [6, 5, 1]])

In [37]:
# stack horizontally
np.hstack((arr, arr2))

array([[3, 9, 2, 0, 4, 2],
       [2, 2, 2, 6, 5, 1]])

In [38]:
# vertically
np.vstack((arr, arr2))

array([[3, 9, 2],
       [2, 2, 2],
       [0, 4, 2],
       [6, 5, 1]])

In [39]:
# combine arrays
np.column_stack((arr, arr2))

array([[3, 9, 2, 0, 4, 2],
       [2, 2, 2, 6, 5, 1]])

In [40]:
np.row_stack((arr, arr2))

array([[3, 9, 2],
       [2, 2, 2],
       [0, 4, 2],
       [6, 5, 1]])

In [41]:
# Split 3x3 array into 3 arrays
arr = np.random.randint(10, size=(3, 3))
arr

array([[7, 5, 6],
       [0, 1, 7],
       [0, 8, 0]])

In [42]:
np.hsplit(arr, 3) # horizontal split into 3 arrays

[array([[7],
        [0],
        [0]]),
 array([[5],
        [1],
        [8]]),
 array([[6],
        [7],
        [0]])]

In [43]:
# make a 2x10 array
arr = np.random.randint(10, size=(2, 10))

In [44]:
# horizontal split after 1st and 2nd column
arr, np.hsplit(arr, (2,6))

(array([[3, 4, 4, 9, 6, 9, 4, 7, 7, 7],
        [8, 5, 9, 9, 0, 1, 9, 6, 6, 7]]),
 [array([[3, 4],
         [8, 5]]),
  array([[4, 9, 6, 9],
         [9, 9, 0, 1]]),
  array([[4, 7, 7, 7],
         [9, 6, 6, 7]])])

### Math funcs

In [45]:
arr = np.array([1, 2, 3, 4, 5])
arr2 = np.array([10, 20, 30, 40, 50])

arr, arr2

(array([1, 2, 3, 4, 5]), array([10, 20, 30, 40, 50]))

In [46]:
# add, sub, mul, div
arr + arr2, arr-arr2, arr*arr2, arr/arr2

(array([11, 22, 33, 44, 55]),
 array([ -9, -18, -27, -36, -45]),
 array([ 10,  40,  90, 160, 250]),
 array([0.1, 0.1, 0.1, 0.1, 0.1]))

In [47]:
# multi dim array of 3x3 from 1 to 50
arrm = np.random.randint(1, 50, (3, 3))
arrm

array([[ 8, 11,  5],
       [23, 17, 46],
       [ 5, 20,  6]])

In [48]:
# a random val from arr
np.random.choice(arr)

3

In [49]:
np.random.seed(13) # seed makes it possible to reproduce random values

In [50]:
np.random.rand(3)

array([0.77770241, 0.23754122, 0.82427853])

In [51]:
np.random.seed(13)
np.random.rand(3)

array([0.77770241, 0.23754122, 0.82427853])

In [52]:
# sum
arr, arr.sum()

(array([1, 2, 3, 4, 5]), 15)

In [53]:
arrm

array([[ 8, 11,  5],
       [23, 17, 46],
       [ 5, 20,  6]])

In [54]:
arrm.sum(axis = 1) #col wise sum

array([24, 86, 31])

In [55]:
# max and min of rows, col wise
arrm.max(axis = 1), arrm.min(axis = 1)

(array([11, 46, 20]), array([ 5, 17,  5]))

In [56]:
np.multiply(arr, arr2)

array([ 10,  40,  90, 160, 250])

In [57]:
np.divide(arr, arr2)

array([0.1, 0.1, 0.1, 0.1, 0.1])

In [58]:
# remainder upon division
np.remainder(arr, arr2)

array([1, 2, 3, 4, 5], dtype=int32)

In [59]:
arr = np.array([[1, 2], [3, 4]])
arr2 = np.array([[2, 4], [6, 9]])

np.power (arr, arr2) # arr to power arr2

array([[     1,     16],
       [   729, 262144]], dtype=int32)

In [60]:
np.sqrt(arr) #square root

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [61]:
np.cbrt(arr) #cube root

array([[1.        , 1.25992105],
       [1.44224957, 1.58740105]])

In [62]:
np.absolute([-2, 0, -5, 90]) #remove signs

array([ 2,  0,  5, 90])

In [63]:
# exp of all items
np.exp(arr)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [64]:
np.log(arr) # log base e 

array([[0.        , 0.69314718],
       [1.09861229, 1.38629436]])

In [65]:
np.log2(arr) # log base 2

array([[0.       , 1.       ],
       [1.5849625, 2.       ]])

In [66]:
np.log10(arr) #log base 10

array([[0.        , 0.30103   ],
       [0.47712125, 0.60205999]])

In [67]:
# greatest common divisor(GCD), Lowest common multiple(LCM)
np.gcd.reduce([9, 12, 15]), np.lcm.reduce([9, 12, 15])

(3, 180)

In [68]:
# round to floor, ceiling

np.floor([1.2, 2.8])

array([1., 2.])

In [69]:
np.ceil([1.2, 2.8])

array([2., 3.])

In [70]:
# argmax --> max value per row
a = np.arange(6).reshape(2,3) + 10
print(a)
np.argmax(a, axis = 0)

[[10 11 12]
 [13 14 15]]


array([1, 1, 1], dtype=int64)

In [71]:
np.argmax(a, axis = 1)

array([2, 2], dtype=int64)

In [72]:
np.sin(a) #trig functions

array([[-0.54402111, -0.99999021, -0.53657292],
       [ 0.42016704,  0.99060736,  0.65028784]])

In [73]:
np.cos(a), np.tan(a)

(array([[-0.83907153,  0.0044257 ,  0.84385396],
        [ 0.90744678,  0.13673722, -0.75968791]]),
 array([[   0.64836083, -225.95084645,   -0.63585993],
        [   0.46302113,    7.24460662,   -0.8559934 ]]))

In [74]:
np.pi #Pi constant

3.141592653589793

In [75]:
np.arcsin(1), np.arccos(1), np.arctan(1)

(1.5707963267948966, 0.0, 0.7853981633974483)

In [76]:
# radian to deg and vice versa
np.rad2deg(np.pi)

180.0

In [77]:
np.deg2rad(180)

3.141592653589793

In [78]:
#hypotenuse func
np.hypot(3, 4)

5.0

### Statistics functions

In [79]:
a = np.arange(1, 10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [80]:
#mean
np.mean(a)

5.0

In [81]:
np.median(a)
#median

5.0

In [82]:
np.average(a)
#average

5.0

In [83]:
np.std(a)
#standard dev

2.581988897471611

In [84]:
np.var(a)
#variance

6.666666666666667

In [85]:
np.percentile(a, 50, axis = 0) #get 50 percentile of a

5.0

### Matrix usecases

In [86]:
arr1 = np.array([2, 3])
arr2 = np.array([3, 2])

#compare functions
np.greater(arr1, arr2)

array([False,  True])

In [87]:
np.less(arr1, arr2)

array([ True, False])

In [88]:
np.greater_equal(arr1, arr2), np.less_equal(arr1, arr2)

(array([False,  True]), array([ True, False]))

In [89]:
np.not_equal(arr1, arr2)

array([ True,  True])

In [90]:
np.equal(arr1, arr2)

array([False, False])

In [91]:
from numpy import linalg as LA

In [92]:
a1 = np.random.randint(1, 5, (2, 2))
a2 = np.random.randint(6, 10, (2, 2))

a1, a2

(array([[1, 2],
        [1, 3]]),
 array([[9, 8],
        [6, 8]]))

In [93]:
np.dot(a1, a2) #dot product

array([[21, 24],
       [27, 32]])

In [94]:
#dot over two or more arrays

a3 = np.random.randint(10, 20, (2, 2))

LA.multi_dot([a1, a2, a3])

array([[ 612,  792],
       [ 804, 1040]])

In [95]:
#inner product
np.inner(a1, a2)

array([[25, 22],
       [33, 30]])

In [96]:
#eigenvalues and eigenvectors
LA.eig(a1)

(array([0.26794919, 3.73205081]),
 array([[-0.9390708 , -0.59069049],
        [ 0.34372377, -0.80689822]]))

In [97]:
LA.eigvals(a1)

array([0.26794919, 3.73205081])

In [98]:
#vector norm --> sqrt(sum(x**2))
LA.norm(a1)

3.872983346207417

In [99]:
#inverse
LA.inv(a1)

array([[ 3., -2.],
       [-1.,  1.]])

In [100]:
#conditional number
LA.cond(a1)

14.933034373659247

In [101]:
# raise matrix to the power of n
# Given [[a, b], [c, d]]
# [[a² + bc, ab + db], [ac + dc, d² + bc]

LA.matrix_power(a1, 2)

array([[ 3,  8],
       [ 4, 11]])

In [102]:
# determinant --> det([[a, b], [c, d]]) = a*d - b*c
LA.det(a1)

1.0

In [103]:
# matrix x its inverse gives identity
np.dot(a1, LA.inv(a1))

array([[1., 0.],
       [0., 1.]])

### Save and load numpy objects


In [104]:
a = np.array([[1, 2], [3, 4]])
np.save('a_array', a) #saves as .npy file on disk

In [105]:
# load 
a1 = np.load('a_array.npy')
a1

array([[1, 2],
       [3, 4]])

In [106]:
# as csv
np.savetxt('a.csv', a)

In [107]:
a2 = np.loadtxt('a.csv')
a2

array([[1., 2.],
       [3., 4.]])

In [108]:
# or load csv via pandas, mor convenient that way